CREATE TABLE ping(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    msg VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO ping (msg) VALUES ('pong desde Oracle');